// Generated by CoffeeScript 1.3.3
var Data;

Data = {
  event_types: ["Favorite", "Follow", "Unfollow", "View Profile", "Send Tweet"],
  props: {
    "origin": ["Twitter", "Facebook", "Google"],
    "country": ["United States", "UK", "France", "Canada", "Mars", "Equatorial Guinea"],
    "page_viewed": ["Homepage", "Login Screen", "Favorites", "Following", "Notifications", "Edit Profile"]
  },
  devices: ["iPhone 4", "iPhone 4S", "iPhone 5", "iPad 1G", "iPad 2", "iPad 3", "Nexus S", "Droid X", "MyTouch 3G", "Xoom"],
  first_names: ["A", "S", "M", "J", "G", "P", "C", "D", "H", "L", "R", "T", "B", "E", "I", "K"],
  last_names: ["Smith", "Philips", "Ryan", "Johnson", "Miller", "Wilson", "Taylor", "Anderson", "Martinez", "Lee", "Hernandez", "Clark", "Robinson", "Young", "Allen", "Lopez", "Wright", "Hill", "Green", "Adams", "Scott", "Lewis", "Baker", "Mitchell", "Roberts", "Evans", "Edwards"]
};
